### ISSUE TITLE
Myrtille machines need to be rebooted after a certain amount of usage?

### ISSUE THREAD

**Issue by BrainSlugs83** [cedrozor/myrtille#126] opened 2018-08-09 20:45 UTC
So, we've been experimenting with Myrtille in two of our services (both services use it in completely different ways), but in both cases, it just stops working at some point until the server is rebooted -- the servers aren't running out of memory, and the CPU utilization is usually around 40% or lower.

On the service that uses Myrtille more heavily (like thousands of connections a day), it needs to be rebooted a couple of times a day to keep Myrtille chugging along; but on the user facing one (which probably does about a hundred a day), it appears to only needs to be rebooted every couple of days or so...

Since memory isn't what's running out, it makes me wonder if there is some other unmanaged resource that Myrtille is using which is sometimes not being properly deallocated? -- I'm unsure what resource that might be, but rebooting the server which is experiencing the issue always fixes the problem.

Can you shed any light on anything we could do to make our Myrtille deployments more stable? (Other than scheduled reboots?)

**Comment by cedrozor** [comment] 2018-08-11 13:58
Nice to hear that Myrtille can handle thousand of connections! :) I tried to make as much load tests as possible, but it's not always easy.

Could you be more accurate about the problem (need for reboot)? if the RAM and CPU are fine, what are the symptoms? (slowness of the web application, or the remote access ?)

When it happens, could you check the system resources (RAM, CPU, network, disk; you can use the resources monitor with windows 10 or performance monitor (aka perflogs) to identify the weakening resource) and the windows event logs (system and application, mostly regarding ASP.NET). You can also check the myrtille logs (located into the myrtille install path, "log" folder).

The FreeRDP C code, and the Myrtille C++ code into FreeRDP, are indeed allocating unmanaged resources, but I tried hard to deallocate everyone of them. There could be some memory leaks (I will recheck that), but if the memory isn't running out, it shouldn't be that.

I'm thinking more of a problem with the application pool ("MyrtilleAppPool") recycling. Did you changed something about that into IIS ? could you try to reduce the recycling interval? default is 1740mn (29 hours), you could try 360mn (6 hours), or based on specific hours.

**Comment by cedrozor** [comment] 2018-08-11 14:01
And also, which version of Myrtille are you using?

**Comment by cedrozor** [comment] 2018-08-15 16:27
Any news ?

**Comment by BrainSlugs83** [comment] 2018-08-24 00:05
Sorry, I've been busy -- (looks like you've been busy too, with new releases) -- I can try to figure out which version each service is using in the next couple of days and get back to you.

Right now I've got them on an automated reboot process to prevent the issue from occurring -- but they're definitely not maxing out CPU or memory -- they just fail to send back images from RDP connections at some point.

I think it might be instances of FreeRDP stacking up that weren't closed gracefully? -- Does the service detect old sessions that haven't had activity and close them automatically? Because I think the IIS service might just be leaving them hanging around a bit too long and forgetting about them or something.

I can work to get you more details in the next week.  Thanks for the response & sorry for the delay. :)

**Comment by cedrozor** [comment] 2018-08-27 20:05
I don't think instances of FreeRDP are stacking up, unless you disabled the idle timeout for the rdp sessions and the myrtille application pool is recycled while some rdp sessions are active.

 There are 3 securities by default:
- if the browser is closed without disconnecting first, the FreeRDP instance is closed and thus the rdp session is disconnected after 1mn.
- if there is no user activity (no inputs), the rdp server disconnects the rdp session after 20mn (idle timeout) and thus the FreeRDP instance is closed.
- the .NET garbage collector is overloaded to disconnect and close the communication pipes (between the FreeRDP instance and the myrtille gateway) prior to releasing them. This have the effect to close the FreeRDP instance (as it loses the ability to read the inputs pipe) and thus disconnect the rdp session.

The problem with the application pool recycling is that it kills the w3wp.exe process (related to the application), which have the effect to free all the related resources (including the pipes handles), but without calling the garbage collector, thus without disconnecting the pipes first.

This can have some unexpected side effects, but shouldn't prevent myrtille from working (as new pipes are created for each new session).

Did you checked if you have something useful into into the windows event logs (system and application, regarding ASP.NET in particular)? also when the problem occurs, have a look to the tasks manager to see if there are unexpected FreeRDP instances (wfreerdp.exe).

You should also enable the myrtille logs (https://github.com/cedrozor/myrtille/blob/master/DOCUMENTATION.md#configuration--performance-tweaks--debug), **RemoteSessionLog** key; don't forget to restart the myrtille service.

**Comment by cedrozor** [comment] 2018-08-28 12:51
I rechecked what happens when some rdp sessions are active and the applications pool is recycled.

The sessions are not disconnected as long the users don't reload their page (F5); if they do, the sessions are disconnected because the related http sessions don't exist anymore. It's not ideal but not bad either.

I think I will disable recycling in the next versions because there is already the garbage collector anyway, which is properly overloaded.

In the meantime, you can disable the recycling of "MyrtilleAppPool" in IIS by following these instructions: https://serverfault.com/questions/333907/what-should-i-do-to-make-sure-that-iis-does-not-recycle-my-application/333948#333948

Please tell me if that fixes the problem (you will need to disable the scheduled reboot to check that).

**Comment by BrainSlugs83** [comment] 2018-08-28 19:10
Thanks, I can give that a try. -- Apologies on the slowness of information coming out of my end.

**Comment by cedrozor** [comment] 2018-09-13 10:02
Did you tried to disable the application pool recycling?

**Comment by MrZakos** [comment] 2018-09-19 09:53
Hi , not sure if to open a new thread or to response here , 
I have this issue also , after a few days of usage , it stops working and I need to restart the service(not the server) in order for it to work again.
It happened on older version 1.6.1 and now I updated to 2.0.1 and still the same issue , on Windows Server 2012. Is this known issue ?I'll try to disable application pool recycling but , but still , something feels off.

**Comment by welsonplay** [comment] 2018-09-19 13:04
I am also facing the same problem. I'll do the same test

**Comment by cedrozor** [comment] 2018-09-20 01:30
@MrZakos Thanks for your feedback, it's important because it pinpoints the issue to the myrtille services instead of web application.

It looks like there is something (idle timeout, concurrent connections limit, unhandled crash, etc ?) that make some or all of the WCF services or callbacks to malfunction (after some time, load or situation) and the way to fix it is to restart Myrtille.Services (and thus the self-hosted WCF services).

It it's a timeout issue, [extend it](https://stackoverflow.com/questions/1520283/wcf-service-how-to-increase-the-timeout) (and eventually set it infinite).

If it's something related to the load (@BrainSlugs83 mentioned thousand of connections), [increase the quotas or limits](https://stackoverflow.com/questions/10275836/what-happens-when-the-maximum-number-of-wcf-connections-is-reached) or perhaps [change the binding type](https://stackoverflow.com/questions/2106715/basichttpbinding-vs-wshttpbinding).

Otherwise, there may be something into the logs. Always check **Myrtille.Services.log** and the other logs into the myrtille log folder.

If you know what you are doing, you can tweak [bin\Myrtille.Services.exe.config](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Services/app.config) and [Web.config](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Web/Web.Base.config) accordingly.

I will take a closer look at this issue asap.

**Comment by MrZakos** [comment] 2018-10-08 08:33
Hi , did you find the root cause ? 
I don't see anything helpful in Myrtille.Services.log file  , how can I send you the log file ?
Tweaking and playing with WCF configuration can be tricky and complicated without finding root cause , like shooting in the dark.
We are currently running a script which restarting the service every day.

**Comment by cedrozor** [comment] 2018-10-16 12:19
Hi, sorry didn't had the time to investigate further.

Could you tell me if you use myrtille in default or enterprise mode? do you have something in the logs (**Myrtille.Web.log** and **Myrille.Services.log** more specifically, into the myrtille log folder). Do you have something in the windows event logs (application and system?).

Thanks!

**Comment by MrZakos** [comment] 2018-10-17 10:50
Hi,

We use default mode ,
didn't find anything in windows events logs ,how can I contact your for sending files ?

**Comment by cedrozor** [comment] 2018-10-17 11:32
You can attach them in a comment for this issue

**Comment by cedrozor** [comment] 2018-11-06 13:20
This is normally fixed into version 2.3.0.

For all those facing (or having faced) this problem, could you check if all is ok now? (and reply in this thread).

**Comment by cedrozor** [comment] 2018-11-21 16:15
Fixed

**Closed by cedrozor** 2018-11-21 16:15 UTC
