### ISSUE TITLE
Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by robdplatt** [cedrozor/myrtille#282] opened 2021-03-04 16:35 UTC
Suddenly started getting this error: `Uncaught ReferenceError: process is not defined`

There's a new issue in the InteractJS package: https://github.com/taye/interact.js/issues/890

Editing Default.aspx to change the InteractJS version back to 1.10.5 resolves this issue for now.
https://github.com/cedrozor/myrtille/blob/058ed822a7de051c9db14df7623357896f437209/Myrtille.Web/Default.aspx#L66

to

`<script language="javascript" type="text/javascript" src="https://cdn.jsdelivr.net/npm/interactjs@1.10.5/dist/interact.min.js"></script>`

**Comment by ChrML** [comment] 2021-03-04 18:57
Same here, everything just stopped working. Seems like an external Content Delivery Network javascript file is referenced. A reference that probably has been changed.

I would recommend packing this as a part of the Docker- image to avoid problems like this caused by external dependencies.

**Comment by cedrozor** [comment] 2021-03-04 23:10
Thanks for the report! I will indeed embed this dependency into Myrtille into the upcoming release.

**Comment by ChrML** [comment] 2021-03-05 07:11
Seems to be working now that `interact.js` have updated to 1.10.7. However probably still a good idea to embed CDN resources like this into Myrtille, so that it's self-contained.

**Comment by cedrozor** [comment] 2021-03-07 16:32
Fixed into [Myrtille 2.9.2](https://github.com/cedrozor/myrtille/releases/tag/v2.9.2)

**Closed by cedrozor** 2021-03-07 16:32 UTC
