### ISSUE TITLE
Allow background and fix the blue mouse shadow

### ISSUE THREAD

**Issue by SieldP** [cedrozor/myrtille#35] opened 2017-01-20 14:09 UTC
Hi cedrozor,

I have two questions:

-  Is it possible to activate the wallpaper with Myrtille ? If yes, Which variable in the solution it is needed to modify?

- I have something like a blue shadow behind the mouse when I am in an RDP session, how can I fix it please ?

 Thank you so much

**Comment by cedrozor** [comment] 2017-01-20 19:57
Hi, the desktop wallpaper is an rdp client option. For simplicity and performance sake, I didn't added it to the UI, but it could be done easily (added in TODO list). You can enable it [here](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Services/RemoteSessionProcess.cs#L99) by setting a network profile adapted to your needs (see the FreeRDP [performance flags](https://github.com/awakecoding/FreeRDP-Manuals/blob/master/User/FreeRDP-User-Manual.markdown#performance-flags) and [network profiles](https://github.com/cedrozor/FreeRDP/blob/master/client/common/cmdline.c#L1092)).

About the mouse cursor, yes this is an issue with the myrtille FreeRDP [fork](https://github.com/cedrozor/FreeRDP) (not sure if I introduced it). There were a lot of commits (seems they are doing a complete overhaul) since I forked the [main repository](https://github.com/FreeRDP/FreeRDP); I wanted to wait a bit before syncing it (to have time to check the new features and there were also some regression reports) but I think it's now a good time to do it now. Also in TODO list.

**Comment by SieldP** [comment] 2017-01-23 15:25
That's perfect for the desktop wallpaper thank you.

About the mouse cursor, I am gonna take a look on this issue. I'll tell you if I solve it.

**Comment by cedrozor** [comment] 2017-01-23 18:24
Nice, please tell me if you solve it. I noticed different behaviors between debug and release builds (so it may have to do with build options). More specifically, I noticed some weird things regarding the mouse cursor and shadow support.

I don't know if I messed something or if this is a freeRDP issue. In doubt, I will resync the fork (https://github.com/cedrozor/FreeRDP) because alot of commits were done recently (they seem to have gone through a big overhaul... lol just after I forked it last september...).

I removed the viewstate because I don't use it and it adds a bunch of code into the HTML (I searched but didn't found a way to disable it in config).

**Comment by cedrozor** [comment] 2017-03-09 10:55
Next release (planned in a few days) will have a FreeRDP debug build. 

I wasn't able to identify the build param which change the mouse cursor behavior (https://github.com/cedrozor/FreeRDP/blob/master/client/Windows/wf_graphics.c#L234) and make it have a blue shadow and (sometimes) not being not updated correctly.

It's weird because I didn't modified the original code and didn't changed any cmake param related to this. There must be an invalid memory/pointer operation, which doesn't make FreeRDP crash but alter its behavior.

I checked the latest FreeRDP commits but found nothing relevant (https://github.com/FreeRDP/FreeRDP/commits/master/client/Windows/wf_graphics.c).

Anyway, the debug build doesn't have this problem and doesn't have a significant impact on performance; so FreeRDP will be in debug build waiting to find the problem.

**Comment by cedrozor** [comment] 2017-06-28 21:53
Fixed in 1.5.0

**Closed by cedrozor** 2017-06-28 21:53 UTC
