### ISSUE TITLE
er 1001

### ISSUE THREAD

**Issue by d7eeem** [cedrozor/myrtille#164] opened 2019-06-27 04:45 UTC
error 1001 : some or all identity references  could not be translated 
Then 
error 1001 cloud not find Files (x86)\Mytille\bin\Mytille.services.InstallStat

**Comment by cedrozor** [comment] 2019-06-27 10:16
Did you installed IIS and .NET 4.5 (or newer)? you can find troubleshooting info here: https://github.com/cedrozor/myrtille/blob/master/DOCUMENTATION.md#troubleshoot

**Comment by datgb** [comment] 2019-06-27 12:29
I actually have both installed on mine. Ill try to do a reinstall of them. net 4.6 is on.

**Comment by cedrozor** [comment] 2019-08-14 17:21
duplicate of https://github.com/cedrozor/myrtille/issues/165 (fixed)

**Closed by cedrozor** 2019-08-14 17:21 UTC
