### ISSUE TITLE
Duplicate session when using both Myrtille and RDP

### ISSUE THREAD

**Issue by adversinc** [cedrozor/myrtille#239] opened 2020-11-10 08:31 UTC
Our users don't reconnect to existing session when mixing Myrtille and regular RDP. Instead, a new session is being launched despite of "Restrict RDS users to a single RDS session" policy set. 

This happens only when mixing Myrtille and RDP:
1. Start first session using RDP, and disconnect
2. Connect using Myrtille and get the second session
and vise-versa.

Can this be fixed/re-configured? We need users to reconnect to existing session with a remote app running. Thank you!

**Comment by cedrozor** [comment] 2020-11-10 21:01
Is your target host a Windows Server 2019? there is a known issue with this OS, with the exact symptoms you described. I explained it there; https://github.com/cedrozor/myrtille/blob/master/DOCUMENTATION.md#remote-desktop-services. A workaround is to lock the session before disconnecting it.

I don't know if this unwanted behavior was fixed or not by a Windows update since. This may also be configurable through a local or group policy.

Because of this issue, I disabled to auto-resize feature of Myrtille by default; it can still be enabled into config.js.

**Comment by sabyasachi-basu-i** [comment] 2020-11-19 11:46
I faced the same issue. The below steps should resolve the problem. Choose either of these methods.

Method 1:
```
In the VM/System open 'gpedit.msc' (Run or Application)
Go to Computer Configuration > Administrative Templates > Windows Components > Remote Desktop Services > Remote Desktop Session Host > Connections
Set Restrict Remote Desktop Services user to a single Remote Desktop Services session to Enabled.
```

Method 2:
```
Open 'regedit'
Set **Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\fSingleSessionPerUser** to **0**
```

If this problem still persists. Review the logs in 
```
Event Viewer > Applications and Services Logs > Microsoft > Windows > Group Policy > Operational
```
and let me know.

**Comment by cedrozor** [comment] 2020-11-19 20:46
Thanks @sabyasachi-basu-i. However, I think you wanted to say for the Method 2:

> 'regedit'
> Set "Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\fSingleSessionPerUser" to "**1**"

The idea is that, if a user is restricted to a single session, it will always reconnect it instead of opening a new one.

The problem is detailed there: https://techcommunity.microsoft.com/t5/windows-server-for-it-pro/bug-no-reconnect-to-disconnected-session-with/m-p/218413

As said earlier in this thread, a workaround is for the user to lock its session before disconnecting it. But that's not practical and most users are unaware of this. A more decent solution is to disable the lock feature, as explained here: https://medium.com/moshe-dicas/windows-2019-rdp-rdsh-not-able-reconnect-to-disconnected-session-every-time-new-session-a1891df6e9c8

After all, when using Myrtille, a user who wants to lock its session (to take a coffee or whatever) will lock _its computer_ and doesn't need to lock it remote session...

For people who need multiple sessions per user, it should be noted that this issue doesn't occurs with Windows Server 2016 and earlier.

**Comment by cedrozor** [comment] 2020-12-30 23:16
Closing. Please re-open if needed.

**Closed by cedrozor** 2020-12-30 23:16 UTC
