### ISSUE TITLE
Domain authentication problem

### ISSUE THREAD

**Issue by c-lillini** [cedrozor/myrtille#76] opened 2017-12-08 18:06 UTC
Hi,
congratulation for your exceptional project.
After merge with the rc version of freerdp (Myrtille 1.6.0), there are problems with domain authentication (it does not even work with the original project).
In the FreeRDP log, i found this:
[ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_PASSWORD_CERTAINLY_EXPIRED [0x0002000F]
but the password is correct and has not expired.
Do you find it?
Thank you.

**Comment by cedrozor** [comment] 2017-12-09 11:06
Hi,
Thanks for the report. It seems that the latest FreeRDP enforce NLA to be enabled on the connected server. See https://github.com/FreeRDP/FreeRDP/issues/4304

**Comment by c-lillini** [comment] 2017-12-10 16:26
Thanks for the answer.
Unfortunately I can not access the server configuration. Have you ever tested domain authentication in version 1.6 of Myrtille?

Thanks!

**Comment by cedrozor** [comment] 2017-12-10 16:59
Yes, I did; but my servers were all having NLA enabled. I will check that asap to find a solution.

**Comment by c-lillini** [comment] 2017-12-10 17:06
Thank you. The next days, I'll try with other servers.

**Comment by c-lillini** [comment] 2017-12-11 18:01
Considering that the problem concerns FreeRDP, I opened the following ticket
https://github.com/FreeRDP/FreeRDP/issues/4310

Thanks!

**Comment by c-lillini** [comment] 2017-12-12 17:24
Hi,
I tried to go back until the following commit https://github.com/cedrozor/FreeRDP/commit/fc8e7ea1a2163a33025c2de05abd08d8856a7d9d and domain authentication works perfectly.
Maybe the problem is the kerberos support https://github.com/cedrozor/FreeRDP/commit/b81f168f0e26241907035eb942204c7fbfd01a77 ?

Thank you!

**Comment by cedrozor** [comment] 2017-12-15 18:25
Hi, probably yes. I already made a pull request (https://github.com/FreeRDP/FreeRDP/pull/4264) to the FeeeRDP team after the myrtille 1.6.0 fork resync which, among other things, introduced kerberos support.  NLA was broken for NTML and Negociate authentication and I fixed it.

I guess there are still some flaws that passed through the kerberos implementation :/ I will investigate that and report it to the FreeRDP team.

**Comment by cedrozor** [comment] 2017-12-22 21:46
I resynced the fork (with the latest FreeRDP master branch) today and wasn't able to reproduce the issue. Did you enabled NLA on your server (should be enabled by default) ? or found a workaround (connecting with /sec:tls or /sec:rdp)?

**Comment by vampywiz17** [comment] 2018-01-10 08:55
affect the same problem. Only work this with 1.5. 

1.6.0 and 1.6.1 not... any (easy) way to solve this issue? (i not a programmer genius, so i cant rebuild the latest master branch on FreeRDP )

**Comment by cedrozor** [comment] 2018-01-10 14:07
Have you enabled NLA on the connected server?

**Comment by vampywiz17** [comment] 2018-01-11 07:16
Yes it is enabled all my server.

**Comment by cedrozor** [comment] 2018-01-12 22:05
I'll try to resync with the latest freerdp branch, hoping they fixed the
issue. It's a 2016 server? Do you have anything specific regarding
configuration?

**Comment by vampywiz17** [comment] 2018-01-14 23:30
Yes, it is a 2016 server, no spec config.

**Comment by cedrozor** [comment] 2018-01-17 17:27
There is an open issue on FreeRDP 2.0 RCx (https://github.com/FreeRDP/FreeRDP/issues/4351), used by myrtille 1.6.x

Can you try to connect using the target IP instead of DNS?

**Comment by cedrozor** [comment] 2018-01-27 15:57
Any news?

**Comment by cedrozor** [comment] 2018-02-07 18:14
Fixed in myrtille version 1.7.0 :)

This gave me a serious headache to track down (I had first to upgrade my VMs to a full domain controlled/load-balanced farm) and fix (there will be PRs to the FreeRDP team) because both FQDN and IPV6 connection are broken into FreeRDP 2.0 RCx, which is quite bad. Hopefully, once the connection is done, all goes well.

The 1st issue with FQDNs involves a strange/weird OpenSSL issue which doesn't occur when using IPs. The errors logged are:
```
[15:50:47:129] [6220:00001924] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_PASSWORD_CERTAINLY_EXPIRED [0x0002000F]
[15:50:47:129] [6220:00001924] [ERROR][com.freerdp.core.transport] - BIO_read returned an error: error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error
[15:50:47:144] [6220:00001924] [ERROR][com.freerdp.core.transport] - BIO_read returned a system error 0: No error
```
Of course, I ensured the password is not expired. I don't know if such issue occurs with OpenSSL 1.1.x (Myrtille uses OpenSSL 1.0.2n, which is the latest 1.0.x version); I tried but didn't succeeced building FreeRDP with it (but I won't give up).

I had workaround it for now by using the target IP instead of FQDN.

The 2nd issue was also severe because, if the client IP address can't be resolved, FreeRDP exits. When using an ipv4 address for the target, all goes well but not with an ipv6 (and FQDNs are translated, using  *getaddrinfo*, into IPV6 if the network supports it). I found that FreeRDP uses a **sockaddr_in**  struct to resolve the ipv6 address whereas it should use a **sockaddr_in6** (now fixed).

The FreeRDP team added quite a lot of new features and code refactoring in the latest commits; this is nice (for example, the RDP 10 support, under Windows Servers 2016, allows to take benefit from hardware acceleration on nvidia cards) but well, I think I will know wait the FreeRDP 2.0 final before resyncing the myrtille FreeRDP fork...

**Comment by cedrozor** [comment] 2018-02-08 13:16
reopen for info and feedback

**Comment by c-lillini** [comment] 2018-02-11 18:51
Good fix @cedrozor! It works perfectly, without NLA enabled also.
Thank you!

**Comment by cedrozor** [comment] 2018-02-11 20:00
Thanks :) it was hard to fix and deep into the freerdp core; I'm surprised noone else had noticed it (it affects not only the windows version, but also android, mac, etc.).

About the ipv6 issue, I alerted the FreeRDP team and @akallabeth made a PR and fixed right away.

So you can now use an FQDN, an IPv4 or IPv6 or NETBIOS name with myrtille 1.7.0, using a connection broker or not, NLA enabled or not, it will work.

**Comment by akallabeth** [comment] 2018-02-12 08:25
Thank you for the fix, it is certainly appreciated.

**Comment by Arcath** [comment] 2018-09-05 09:45
I'm using 2.1.2 and getting this problem.

I've tried just using an IP for the domain controller with `Domain Admins` as the management group and its constantly asking me to change my password.

Where is the freerdp log stored? there is nothing in Myrtille/logs.

This isn't even at the point of trying to connect to a rdp session, just login to view the server list.

I've tried with and without NLA on the Domain Controller and it does it with both.

**Comment by Arcath** [comment] 2018-09-05 09:58
Myrtille 2.0.0 works but you have to specify hosts etc...

Myrtille 2.1.0 has the same fault.

**Comment by cedrozor** [comment] 2018-09-05 17:52
> I'm using 2.1.2 and getting this problem.
> 
> I've tried just using an IP for the domain controller with Domain Admins as the management group and its constantly asking me to change my password.

Into Myrtilles.services.exe.config (myrtille install path, bin folder), is `EnterpriseNetbiosDomain` empty? (should be if you use an IP for `EnterpriseDomain`).

@bigpjo could you take a look at it? (about the constant request to change the password)

> 
> Where is the freerdp log stored? there is nothing in Myrtille/logs.
> 
> This isn't even at the point of trying to connect to a rdp session, just login to view the server list.
> 
> I've tried with and without NLA on the Domain Controller and it does it with both.

wfreerdp has nothing to do with the problem neither the connection security mode (NLA); the problem is related to the enterprise mode, to display the hosts list (if I understand well?). 

But if you want to enable the wfreerdp logs, you have to set the `RemoteSessionLog` key to "true" into Myrtilles.services.exe.config.

Every change into Myrtilles.services.exe.config needs the myrtille service to be restarted.

> Myrtille 2.0.0 works but you have to specify hosts etc...
> 
> Myrtille 2.1.0 has the same fault.

What do you mean by "you have to specify hosts"?

**Comment by Arcath** [comment] 2018-09-05 21:08
> What do you mean by "you have to specify hosts"?

Myrtille asks the end user for the host instead of letting me setup a list of hosts for the user to connect to.

**Comment by bigpjo** [comment] 2018-09-06 22:05
Hi adam

Have you correctly configured enterprise mode in you
myrtille.service.config file?

**Comment by Arcath** [comment] 2018-09-10 08:39
My config is:

```
    <add key="EnterpriseAdapter" value="Myrtille.Enterprise.ActiveDirectory, Myrtille.Enterprise" />
    <add key="EnterpriseAdminGroup" value="Domain Admins" />
    <add key="EnterpriseDomain" value="poulton.local" />
    <add key="EnterpriseNetbiosDomain" value="POULTON" />
```

**Comment by Arcath** [comment] 2018-09-13 09:12
I have figured out what was causing my problem!

I use a group policy to set the password expiration to `0` (_Never expires_). This means that passwords never expire in that the computers/domain controllers will never tell a logging in user that their password has expired. Evidently, it doesn't mean that AD won't report an expired password. Setting a user to `Password Never Expires` in AD fixes the issue.

It's still a little odd as I had just created a user (Password age of 5 minutes) and it asked them to change it all the time until I ticked password never expires.

**Comment by bigpjo** [comment] 2018-09-13 09:14
Hi adam

Glad you reported the issue but you have found a work around.

I will have a look at this

**Comment by cedrozor** [comment] 2018-10-16 12:21
Hi Paul, any news on this? thanks!

**Comment by bigpjo** [comment] 2018-10-16 14:46
Hi cedric.

I am looking at it today.

Thabks

Paul

**Comment by cedrozor** [comment] 2018-11-21 16:17
Paul, do you want me to check this?

**Comment by cedrozor** [comment] 2019-01-12 15:35
I will have a look at it into the next release

**Closed by cedrozor** 2019-01-12 15:35 UTC

**Comment by scerazy** [comment] 2019-03-20 12:08
Anything more?

sebus

**Comment by cedrozor** [comment] 2020-01-05 16:00
Fixed in the upcoming version
