### ISSUE TITLE
Crashes after pressing Clipboard and than Close button and won't connect util reboot.

### ISSUE THREAD

**Issue by romanad** [cedrozor/myrtille#181] opened 2019-11-17 19:37 UTC
Hello, dear Developer.

The steps I made:
1) Uninstalled 2.5.5 
2) Installed brand new 2.7.0.0
My OS is Windows 10 Pro x64 1903 with latest updates (truly licensed).

And now my Myrtille crashes after pressing Clipboard and than Close button and won't connect util reboot.

Sometimes it disconnects when you press send. It seems to crash randomly with Clipboard dialog.

: (

**Comment by cedrozor** [comment] 2019-11-18 14:53
Hi,

Thanks for your report. Does it also happen with a clipboard paste action (ctrl+v) within the remote session or only with the clipboard dialog (when pressing send)?

**Comment by romanad** [comment] 2019-11-18 15:25
Tried today all the same with no issues and without any software changes, Idk maybe it was happening because of junk cache of previous 2.5.5 version. Also tried on Firefox and no issue was noticed.
Maybe the ticket can be closed : )

**Comment by cedrozor** [comment] 2019-11-18 16:44
Maybe a browser cache issue yes, I will have a closer look. This is more unlikely with the 2.7.0 however, because I had the javascript files bundled with a version hash from the default page.

**Comment by cedrozor** [comment] 2019-11-19 16:12
I wasn't able to reproduce the issue.  It may be related to a specific clipboard content (?) Closing for now, please re-open if needed.

**Closed by cedrozor** 2019-11-19 16:12 UTC
